#!/usr/bin/env sh

URL=http://localhost
RESOLUTION=$(DISPLAY=:0 xrandr --query 2>/dev/null | grep "^ *[0-9]" | awk '{ print $1 }' | tr -s 'x' ',')

xset -dpms
xset s off
xset s noblank

unclutter &
chromium-browser ${URL} \
  --window-size=${RESOLUTION} \
  --window-position=0,0 \
  --start-fullscreen \
  --kiosk \
  --incognito \
  --noerrdialogs \
  --disable-translate \
  --no-first-run \
  --fast \
  --fast-start \
  --disable-infobars \
  --disable-features=TranslateUI \
  --disk-cache-dir=/dev/null \
  --overscroll-history-navigation=0 \
  --disable-pinch
